# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('waffle', '0003_update_strings_for_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waffle_flags', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waffle_samples', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='switch',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waffle_switches', to='sites.Site'),
        ),
    ]
